### PR TITLE
Replace message 'Throttle value for arming' with 'Throttle limit for arming'

### PR DESCRIPTION
**Pull request by AndersHoglund**
Rephrase menu message text to 'Throttle limit for arming' in order to make it a little bit clearer for new users what this actually is all about.
Chinese messages not touched. Not sure NL translation is correct, copied directly from google translate.

### CODE REVIEW

**Review by rotorflight — CHANGES_REQUESTED** [review]
Only change the translations, if the translation has been done, and the meaning is 100% matching the english message

**Comment by rotorflight** [comment]
In this case, only the en and de are valid. The other changes are incorrect.

**Comment by AndersHoglund** [comment]
> In this case, only the en and de are valid. The other changes are incorrect.
I can agree the two ch_CN and ch_TW are incorrect, probably different wording in translated and english texts. In all others I did try to use google translate correctly. But then there are those where the translated (to be) text is a copy of the english. Both are then rephrased. We need the same wording regardless of lingo chosen. Chineze would then be the only problem, I could add a "status:..."-line saying something like "English text rephrased, please re-translate". Some of the non-translations have this, some don't. Maybe add status there too?

**Comment by rotorflight** [comment]
That's all automated, but it only works if the translations are kept correct, i.e. the english message matches the translated message. If you don't fix the translation, then touch the file at all. The translation tools will later collect the work for the translators to fix it.

**Comment by AndersHoglund** [comment]
But the translated messages _do_ match the English messages, even in non-translated files where both are in English. Except for ch_CN and ch_TW. Would not a new status line trigger the ch translators to re-phrase? How else to manage maintenance of changes in menu texts?  Translations are a nightmare for maint.
Easy fix, close this PR without further actions. Only tried to help.

**Comment by AndersHoglund** [comment]
OK, thanks. But what am I supposed to do? Fix ch_ files as suggested? Do nothing?

**Comment by rotorflight** [comment]
Merged manually. Thanks.

**Pull request closed without merging**
