### PR TITLE
Update and unhide Traditional Chinese (zh_TW) locale

### PR DESCRIPTION
**Pull request by drung0418**
Based on zh_CN to translate the whole locale for zh_TW.
All computer science proper nouns were translated based on TW's translation rule.
Other terms were translated based on what we use between TW's helicopter players.

### CODE REVIEW

**Comment by rotorflight** [comment]
There are 29 un-translated entries. Can you translate those too please.

**Comment by drung0418** [comment]
done, already translate all "un-translated" entries and update all modified entries by new description.

**Comment by drung0418** [comment]
done, here is everything I have right now.

**Comment by drung0418** [comment]
Locale already merged back by Dr. directly. Close this PR.

**Pull request closed without merging**
